# Generated by Django 5.2.11 on 2026-05-06 06:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('sha_number', models.CharField(blank=True, help_text='SHA / NHIF membership number', max_length=30)),
                ('insurance_provider', models.CharField(blank=True, help_text='e.g. AIR, BRITAM, SHA, JUBILEE', max_length=50)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('admin', 'Admin')], default='receptionist', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('patch', 'Patch'), ('other', 'Other')], max_length=20)),
                ('strength', models.CharField(help_text='e.g. 500mg, 250mg/5ml', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'strength', 'dosage_form')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('OPD', 'Outpatient (OPD)'), ('IPD', 'Inpatient (IPD)'), ('EMERGENCY', 'Emergency'), ('FOLLOWUP', 'Follow-up')], default='OPD', max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('triage', 'In Triage'), ('waiting', 'Waiting for Doctor'), ('with_doctor', 'With Doctor'), ('radiology', 'Sent to Radiology'), ('pharmacy', 'Sent to Pharmacy'), ('billing', 'Sent to Billing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('attending_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='core.patient')),
                ('registered_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptionist_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='SpO2 %', max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('chief_complaint', models.TextField()),
                ('urgency_level', models.CharField(choices=[('green', 'Green  — Non-urgent'), ('yellow', 'Yellow — Urgent'), ('red', 'Red    — Critical')], default='green', max_length=10)),
                ('triaged_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_triages', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='core.visit')),
            ],
            options={
                'ordering': ['-triaged_at'],
            },
        ),
        migrations.CreateModel(
            name='SHARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_provider', models.CharField(choices=[('SHA', 'Social Health Authority (SHA)'), ('NHIF', 'NHIF (Legacy)'), ('AIR', 'AAR Insurance Kenya'), ('BRITAM', 'Britam Insurance'), ('JUBILEE', 'Jubilee Health Insurance'), ('MADISON', 'Madison Insurance'), ('RESOLUTION', 'Resolution Insurance'), ('CASH', 'Self-Pay (Cash)'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('member_number', models.CharField(blank=True, max_length=50)),
                ('pre_authorization_code', models.CharField(blank=True, max_length=50)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('patient_copay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('claim_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Approved')], default='pending', max_length=20)),
                ('claim_reference', models.CharField(blank=True, help_text='Reference number from insurer', max_length=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sha_records', to='core.patient')),
                ('submitted_by', models.ForeignKey(limit_choices_to={'role': 'cashier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_claims', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sha_record', to='core.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_presenting_illness', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('diagnosis', models.CharField(help_text='Primary diagnosis (ICD-10 preferred)', max_length=255)),
                ('secondary_diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment_plan', models.TextField(blank=True)),
                ('prescriptions', models.TextField(blank=True, help_text='Drug name, dose, frequency, duration')),
                ('referred_to_radiology', models.BooleanField(default=False)),
                ('radiology_request_notes', models.TextField(blank=True)),
                ('referred_to_pharmacy', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_records', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
